### ISSUE TITLE
each student added to repo

### ISSUE THREAD

**Issue by 12oman** [12oman/cf-24#1]
# To-Do List for Flexbox Lesson

## Each student needs to be added to this repository and add their link in the html file.

- [x] Steph @ ss1mba
- [X] Liv @L1VB 
- [X] Tai @T4IBrownnn 
- [x] Valentina @valentinacianci 
- [X] Lena @LenaCrafter 
- [X] Alyssa @rrussianfairyy 
- [X] Alex @escAlexHJ 
- [X] Grace @gracekinii 
- [X] Fenn @rainbowsluggg 
- [X] Milla @millapyne 
- [X] Leo @leosamson 
- [X] Nate @nateskinnerr 
- [X] Ramona @Ramonabeepbop 
- [X] Mark @Yttll 
- [X] Seta @Setamushroom 

Roman

**Comment by 12oman** [comment]
@bigfatfish8 not sure who this is? :)

**Comment by 12oman** [comment]
### moved Not Added to seperate issue
- [ ] Kambi
- [ ] Brook
- [ ] Carter
- [ ] Lizzie
- [ ] Nicole
- [ ] B
- [ ] Christiana

**Comment by rrussianfairyy** [comment]
Hello Roman

Yes I started off the class website with a draft design with some Sanrio characters and stuff and I’m currently adding 22 positions too it so everyone can add their repo link. It’s a bit chaotic and no one is in class really so I can’t get a hold of them. Also so far I'm the only one  working on the class collaborative website and I’m not sure if people even know what to do but I don’t mind taking the initiative on doing it I’ll just be happy if ppl add their repos to the example links I’ve put in the index html code.

Also I hope you feel better soon!

Alyssa

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
